### ISSUE TITLE
incompatible with scalaz 7.1 and play 2.4

### ISSUE THREAD

**Issue by dgouyette** [Kanaka-io/play-monadic-actions#8]
It seems play-monadic-actions is not compatible with play 2.4 ans scalaz 7.1, see stacktrace below : 

`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: scalaz.syntax.Syntaxes$id$.ToIdOps(Ljava/lang/Object;)Lscalaz/syntax/IdOps;]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.3.jar:2.4.3]
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.3.jar:2.4.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.3.jar:2.4.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.3.jar:2.4.3]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: scalaz.syntax.Syntaxes$id$.ToIdOps(Ljava/lang/Object;)Lscalaz/syntax/IdOps;
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:498) ~[play_2.11-2.4.3.jar:2.4.3]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.3.jar:2.4.3]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.3.jar:2.4.3]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.3.jar:2.4.3]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.3.jar:2.4.3]
Caused by: java.lang.NoSuchMethodError: scalaz.syntax.Syntaxes$id$.ToIdOps(Ljava/lang/Object;)Lscalaz/syntax/IdOps;
    at controllers.ActionDSL.package$.fromTry(ActionDSL.scala:70) ~[play-monadic-actions_2.11-1.0.1.jar:1.0.1]
    at controllers.ActionDSL.package$MonadicActions$$anon$12.orFailWith(ActionDSL.scala:137) ~[play-monadic-actions_2.11-1.0.1.jar:1.0.1]
    at controllers.ActionDSL.package$StepOps$class.$qmark$bar(ActionDSL.scala:76) ~[play-monadic-actions_2.11-1.0.1.jar:1.0.1]
    at controllers.ActionDSL.package$MonadicActions$$anon$12.$qmark$bar(ActionDSL.scala:136) ~[play-monadic-actions_2.11-1.0.1.jar:1.0.1]
    at controllers.MonitoringController.checkMongo(MonitoringController.scala:65) ~[classes/:2.4.0-1]`

**Comment by drbild** [comment]
Fixed by b039be661661d309183beebea7d7058118ffe69b
